using System.Collections.Generic;
public static partial class AirportCatalog {
    // OurAirports: nomes consultados em 14/09/2026, domínio público. Cidades permanecem no catálogo original.
    public static readonly Dictionary<string, string> Names = new Dictionary<string, string> {
        { "AAI", "Arraias Airport" },
        { "AAX", "Romeu Zema Airport" },
        { "AFL", "Piloto Osvaldo Marques Dias Airport" },
        { "AIF", "Marcelo Pires Halzhausen Airport" },
        { "AIR", "Aripuanã Airport" },
        { "AIY", "Araçuaí Airport" },
        { "AJU", "Aracaju - Santa Maria Airport" },
        { "ALQ", "Alegrete Novo Airport" },
        { "ALT", "Alenquer Municipal Airport" },
        { "AMJ", "Cirilo Queiróz Airport" },
        { "APQ", "Arapiraca Airport" },
        { "APS", "Anápolis Airport" },
        { "APU", "Captain João Busse Airport" },
        { "APX", "Arapongas Airport" },
        { "APY", "Alto Parnaíba Airport" },
        { "AQA", "Araraquara Airport" },
        { "AQM", "Ariquemes Airport" },
        { "ARS", "Aragarças Airport" },
        { "ARU", "Araçatuba Airport" },
        { "ARX", "Aracati Dragão do Mar Regional Airport" },
        { "ATM", "Altamira Interstate Airport" },
        { "AUX", "Araguaína Airport" },
        { "AXE", "Xanxerê Airport" },
        { "AZL", "Fazenda Tucunaré Airport" },
        { "BAT", "Chafei Amsei Airport" },
        { "BAZ", "Barcelos Airport" },
        { "BCR", "Novo Campo Airport" },
        { "BDC", "Barra do Corda Airport" },
        { "BEL", "Val de Cans/Júlio Cezar Ribeiro International Airport" },
        { "BFH", "Bacacheri Airport" },
        { "BGV", "Aeroclube de Bento Gonçalves Airport" },
        { "BGX", "Comandante Gustavo Kraemer Airport" },
        { "BJP", "Estadual Arthur Siqueira Airport" },
        { "BMS", "Sócrates Mariani Bittencourt Airport" },
        { "BNU", "Blumenau Airport" },
        { "BPG", "Barra do Garças Airport" },
        { "BPS", "Porto Seguro International Airport" },
        { "BQQ", "Barra Airport" },
        { "BRA", "Dom Ricardo Weberberger Airport" },
        { "BRB", "Barreirinhas National Airport" },
        { "BSB", "Presidente Juscelino Kubitschek International Airport" },
        { "BSS", "Balsas Airport" },
        { "BVB", "Atlas Brasil Cantanhede International Airport" },
        { "BVH", "Brigadeiro Camarão Airport" },
        { "BVM", "Belmonte Airport" },
        { "BVS", "Breves Airport" },
        { "BYO", "Bonito Airport" },
        { "BZC", "Umberto Modiano Airport" },
        { "CAC", "Coronel Adalberto Mendes da Silva Airport" },
        { "CAF", "Carauari Airport" },
        { "CAU", "Caruaru Airport" },
        { "CAW", "Bartolomeu Lisandro Airport" },
        { "CBW", "Campo Mourão Airport" },
        { "CCI", "Olavo Cecco Rigon Airport" },
        { "CCM", "Forquilhinha - Criciúma  Airport" },
        { "CCX", "Cáceres Airport" },
        { "CDI", "Cachoeiro do Itapemirim - Raimundo de Andrade Airport" },
        { "CDJ", "Conceição do Araguaia Airport" },
        { "CEL", "Canela Airport" },
        { "CFB", "Cabo Frio Airport" },
        { "CFC", "Doctor Carlos Alberto da Costa Neves Airport" },
        { "CFO", "Confresa Airport" },
        { "CGB", "Várzea Grande–Marechal Rondon International Airport" },
        { "CGH", "Congonhas–Deputado Freitas Nobre Airport" },
        { "CGR", "Campo Grande Airport" },
        { "CHD", "Mucugê Airport" },
        { "CIZ", "Danilson Municipal Airport" },
        { "CJZ", "Pedro Vieira Moreira Airport" },
        { "CKO", "Cornélio Procópio Airport" },
        { "CKS", "Carajás Airport" },
        { "CLN", "Brig. Lysias Augusto Rodrigues Airport" },
        { "CLV", "Nelson Ribeiro Guimarães Airport" },
        { "CMC", "Camocim - Pinto Martins Airport" },
        { "CMG", "Corumbá International Airport" },
        { "CMP", "Santana do Araguaia Airport" },
        { "CMT", "New Cametá Airport" },
        { "CNF", "Tancredo Neves International Airport" },
        { "CNV", "Sócrates Rezende Airport" },
        { "CPU", "Cururupu Airport" },
        { "CPV", "Presidente João Suassuna Airport" },
        { "CQA", "Canarana Airport" },
        { "CQS", "Costa Marques Airport" },
        { "CRQ", "Caravelas Airport" },
        { "CSS", "Cassilândia Airport" },
        { "CSU", "Santa Cruz do Sul Airport" },
        { "CTP", "Carutapera Airport" },
        { "CTQ", "Santa Vitória do Palmar Airport" },
        { "CWB", "Curitiba-Afonso Pena International Airport" },
        { "CXJ", "Hugo Cantergiani Regional Airport" },
        { "CZB", "Carlos Ruhl Airport" },
        { "CZS", "Cruzeiro do Sul Airport" },
        { "DIQ", "Brigadeiro Cabral Airport" },
        { "DMT", "Diamantino Airport" },
        { "DNO", "Dianópolis Airport" },
        { "DOU", "Dourados Airport" },
        { "DTI", "Diamantina Airport" },
        { "EEA", "Planalto Serrano Regional Airport" },
        { "ERM", "Erechim Airport" },
        { "ERN", "Eirunepé Airport" },
        { "FBA", "Fonte Boa Airport" },
        { "FBE", "Paulo Abdala Airport" },
        { "FEC", "João Durval Carneiro Airport" },
        { "FEJ", "Feijó Airport" },
        { "FEN", "Fernando de Noronha Airport" },
        { "FLB", "Cangapara Airport" },
        { "FLN", "Hercílio Luz International Airport" },
        { "FOR", "Pinto Martins International Airport" },
        { "FRC", "Tenente Lund Pressoto Airport" },
        { "GCV", "Gravatai Airport" },
        { "GDP", "Guadalupe Airport" },
        { "GDR", "Angra dos Reis Airport" },
        { "GEL", "Santo Ângelo Airport" },
        { "GGB", "Frederico Carlos Müller Airport" },
        { "GGF", "Almeirim Airport" },
        { "GGH", "Engenheiro Gastão de Mesquita Filho Airport" },
        { "GGJ", "Guaíra Airport" },
        { "GIG", "Rio de Janeiro Galeão – Tom Jobim International Airport" },
        { "GJM", "Guajará-Mirim Airport" },
        { "GMS", "Antônio Guerreiro Airport" },
        { "GNM", "Guanambi Airport" },
        { "GPB", "Tancredo Thomas de Faria Airport" },
        { "GRP", "Gurupi Airport" },
        { "GRU", "São Paulo/Guarulhos–Governor André Franco Montoro International Airport" },
        { "GUJ", "Edu Chaves Field" },
        { "GUZ", "Guarapari Airport" },
        { "GVR", "Coronel Altino Machado Airport" },
        { "GYN", "Santa Genoveva International Airport" },
        { "HRZ", "Walter Bündchen Airport" },
        { "HUW", "Humaitá Airport" },
        { "IDO", "Santa Izabel do Morro Airport" },
        { "IGU", "Cataratas International Airport" },
        { "IJU", "João Batista Bos Filho Airport" },
        { "IMP", "Prefeito Renato Moreira Airport" },
        { "IOS", "Bahia - Jorge Amado Airport" },
        { "IPG", "Ipiranga Airport" },
        { "IPN", "Usiminas Airport" },
        { "IPU", "Ipiaú Airport" },
        { "IRE", "Irecê Airport" },
        { "IRZ", "Tapuruquara Airport" },
        { "ITA", "Itacoatiara Airport" },
        { "ITB", "Itaituba Airport" },
        { "ITE", "Ituberá Airport" },
        { "ITI", "Fazenda Americana Airport" },
        { "ITJ", "Campo Comandantes Airport" },
        { "ITN", "Tertuliano Guedes de Pinho Airport" },
        { "ITP", "Itaperuna Airport" },
        { "ITQ", "Itaqui Airport" },
        { "ITR", "Francisco Vilela do Amaral Airport" },
        { "IUP", "Apuí Airport" },
        { "IZA", "Presidente Itamar Franco Airport" },
        { "JAW", "Araripina Airport" },
        { "JBS", "São Borja Airport" },
        { "JCB", "Santa Terezinha Airport" },
        { "JCM", "Jacobina Airport" },
        { "JCR", "Jacareacanga Airport" },
        { "JCS", "Crateús Airport" },
        { "JDF", "Francisco de Assis Airport" },
        { "JDO", "Orlando Bezerra de Menezes Airport" },
        { "JDR", "Prefeito Octávio de Almeida Neves Airport" },
        { "JEQ", "Jequié Airport" },
        { "JHF", "São Paulo Catarina Executive Airport" },
        { "JIA", "Juína Airport" },
        { "JJD", "Comandante Ariston Pessoa Airport" },
        { "JJG", "Humberto Ghizzo Bortoluzzi Regional Airport" },
        { "JLS", "Jales Airport" },
        { "JMA", "Aeroporto Elias Breder Airport" },
        { "JMR", "Maricá Airport" },
        { "JNA", "Januária Airport" },
        { "JOI", "Lauro Carneiro de Loyola Airport" },
        { "JPA", "Presidente Castro Pinto International Airport" },
        { "JPE", "Nagib Demachki Airport" },
        { "JPO", "Aeroporto Brigadeiro Firmino Ayres" },
        { "JPR", "Ji-Paraná Airport" },
        { "JPY", "Paraty Airport" },
        { "JRN", "Juruena Airport" },
        { "JRT", "Juruti Airport" },
        { "JSB", "Walfrido Salmito de Almeida Airport" },
        { "JSO", "Dr. Luciano de Arruda Coelho Regional Airport" },
        { "JTA", "Pedro Teixeira Castelo Airport" },
        { "JTC", "Bauru/Arealva–Moussa Nakhal Tobias State Airport" },
        { "JTI", "Jataí Airport" },
        { "JTN", "Itanhaém Airport" },
        { "JUA", "Inácio Luís do Nascimento Airport" },
        { "LAJ", "Lages Airport" },
        { "LAZ", "Bom Jesus da Lapa Airport" },
        { "LBR", "Lábrea Airport" },
        { "LCB", "André Antônio Maggi Airport" },
        { "LDB", "Governor José Richa Airport" },
        { "LEC", "Coronel Horácio de Mattos Airport" },
        { "LEP", "Leopoldina Airport" },
        { "LHN", "Linhares Municipal Airport" },
        { "LIP", "Lins Airport" },
        { "LOI", "Helmuth Baungarten Airport" },
        { "LVR", "Municipal Bom Futuro Airport" },
        { "MAB", "João Correa da Rocha Airport" },
        { "MAO", "Eduardo Gomes International Airport" },
        { "MBK", "Orlando Villas Boas Regional Airport" },
        { "MBZ", "Maués Airport" },
        { "MCP", "Macapá - Alberto Alcolumbre International Airport" },
        { "MCZ", "Zumbi dos Palmares International Airport" },
        { "MEA", "Macaé Benedito Lacerda Airport" },
        { "MEU", "Monte Dourado - Serra do Areão Airport" },
        { "MGF", "Regional de Maringá - Sílvio Name Júnior Airport" },
        { "MII", "Frank Miloye Milenkowichi–Marília State Airport" },
        { "MNX", "Manicoré Airport" },
        { "MOC", "Mário Ribeiro Airport" },
        { "MQH", "Minaçu Airport" },
        { "MTE", "Monte Alegre Airport" },
        { "MTG", "Vila Bela da Santíssima Trindade Airport" },
        { "MUU", "Barra Grande Airport" },
        { "MVF", "Dix-Sept Rosado Airport" },
        { "MVS", "Mucuri Airport" },
        { "MXQ", "Lorenzo Airport" },
        { "NAT", "Rio Grande do Norte/São Gonçalo do Amarante–Governador Aluízio Alves International Airport" },
        { "NNU", "Nanuque Airport" },
        { "NOK", "Xavantina Airport" },
        { "NPR", "Novo Progresso Airport" },
        { "NQL", "Niquelândia Airport" },
        { "NSR", "Serra da Capivara Airport" },
        { "NVM", "Brigadeiro Eduardo Gomes Airport" },
        { "NVP", "Novo Aripuanã Airport" },
        { "NVT", "Ministro Victor Konder International Airport" },
        { "OAL", "Cacoal Airport" },
        { "OBI", "Óbidos Municipal Airport" },
        { "OIA", "Ourilândia do Norte Airport" },
        { "OLC", "Senadora Eunice Micheles Airport" },
        { "OPP", "Salinópolis Airport" },
        { "OPS", "Presidente João Batista Figueiredo Airport" },
        { "ORX", "Oriximiná Airport" },
        { "OTT", "Andre Maggi Airport" },
        { "OUS", "Jornalista Benedito Pimentel Airport" },
        { "OYK", "Oiapoque Airport" },
        { "PAV", "Paulo Afonso Airport" },
        { "PBA", "Fábio Perini Airport" },
        { "PBB", "Paranaíba Airport" },
        { "PBQ", "Pimenta Bueno Airport" },
        { "PBX", "Fazenda Piraguassu Airport" },
        { "PCS", "Picos Airport" },
        { "PDF", "Prado Airport" },
        { "PDR", "Presidente José Sarney Airport" },
        { "PET", "João Simões Lopes Neto International Airport" },
        { "PFB", "Lauro Kurtz Airport" },
        { "PGZ", "Ponta Grossa Airport - Comandante Antonio Amilton Beraldo" },
        { "PHB", "Parnaíba - Prefeito Doutor João Silva Filho International Airport" },
        { "PHI", "Pinheiro Airport" },
        { "PIN", "Parintins Airport" },
        { "PIV", "Pirapora Airport" },
        { "PLL", "Ponta Pelada Airport / Manaus Air Base" },
        { "PLU", "Pampulha - Carlos Drummond de Andrade Airport" },
        { "PMG", "Ponta Porã Airport" },
        { "PMW", "Brigadeiro Lysias Rodrigues Airport" },
        { "PNB", "Porto Nacional Airport" },
        { "PNG", "Paranaguá Airport" },
        { "PNZ", "Senador Nilo Coelho Airport" },
        { "POA", "Porto Alegre-Salgado Filho International Airport" },
        { "POJ", "Patos de Minas Airport" },
        { "POO", "Poços de Caldas - Embaixador Walther Moreira Salles Airport" },
        { "PPB", "Presidente Prudente Airport" },
        { "PPY", "Pouso Alegre Airport" },
        { "PSW", "José Figueiredo Municipal Airport" },
        { "PTO", "Juvenal Loureiro Cardoso Airport" },
        { "PTQ", "Porto de Moz Airport" },
        { "PVH", "Governador Jorge Teixeira de Oliveira International Airport" },
        { "PVI", "Paranavaí Airport" },
        { "PYT", "Pedro Rabelo de Souza Airport" },
        { "QCH", "Colatina Airport" },
        { "QCP", "Currais Novos Airport" },
        { "QDB", "Cachoeira do Sul Airport" },
        { "QDV", "Comte. Rolim Adolfo Amaro–Jundiaí State Airport" },
        { "QGF", "Montenegro Airport" },
        { "QGP", "Garanhuns Airport" },
        { "QHV", "Novo Hamburgo Airport" },
        { "QIG", "Iguatu Airport" },
        { "QIT", "Itapetinga Airport" },
        { "QNS", "Canoas Air Force Base" },
        { "QSC", "Mário Pereira Lopes–São Carlos International Airport" },
        { "RAO", "Leite Lopes Airport" },
        { "RBB", "Borba Airport" },
        { "RBR", "Rio Branco-Plácido de Castro International Airport" },
        { "RDC", "Redenção Airport" },
        { "REC", "Recife/Guararapes - Gilberto Freyre International Airport" },
        { "REZ", "Resende Airport" },
        { "RIA", "Santa Maria Airport" },
        { "RIG", "Rio Grande Regional Airport" },
        { "ROO", "Maestro Marinho Franco Airport" },
        { "RPU", "Urucu Airport" },
        { "RRJ", "Jacarepaguá - Roberto Marinho Airport" },
        { "RTE", "Campo de Marte Airport" },
        { "RVD", "General Leite de Castro Airport" },
        { "SBJ", "São Mateus - Ernesto Bonomo Airport" },
        { "SDU", "Santos Dumont Airport" },
        { "SET", "Santa Magalhães Airport" },
        { "SFK", "Soure Airport" },
        { "SFV", "Santa Fé do Sul Airport" },
        { "SJK", "Professor Urbano Ernesto Stumpf Airport" },
        { "SJL", "São Gabriel da Cachoeira Airport" },
        { "SJP", "Prof. Eribelto Manoel Reino State Airport" },
        { "SLZ", "Marechal Cunha Machado International Airport" },
        { "SMT", "Adolino Bedin Regional Airport" },
        { "SNZ", "Santa Cruz Air Force Base" },
        { "SOD", "Sorocaba Airport" },
        { "SQM", "São Miguel do Araguaia Airport" },
        { "SQX", "São Miguel do Oeste Hélio Wasum Airport" },
        { "SQY", "São Lourenço do Sul Airport" },
        { "SRA", "Luis Alberto Lehr Airport" },
        { "SSA", "Deputado Luiz Eduardo Magalhães International Airport" },
        { "SSO", "São Lourenço Airport" },
        { "SSZ", "Santos Nero Moura Air Base / Guarujá Airport" },
        { "STM", "Santarém - Maestro Wilson Fonseca International Airport" },
        { "SXO", "São Félix do Araguaia Airport" },
        { "SXX", "São Félix do Xingu Airport" },
        { "TBT", "Tabatinga International Airport" },
        { "TEC", "Telêmaco Borba Airport" },
        { "TFF", "Tefé Airport" },
        { "TFL", "Juscelino Kubitscheck Airport" },
        { "TGQ", "Tangará da Serra Airport" },
        { "THE", "Senador Petrônio Portela Airport" },
        { "TJL", "Plínio Alarcom Airport" },
        { "TLZ", "Catalão Airport" },
        { "TMT", "Trombetas Airport" },
        { "TOW", "Toledo - Luiz Dalcanale Filho Municipal Airport" },
        { "TRQ", "Tarauacá Airport" },
        { "TSQ", "Torres Airport" },
        { "TUR", "Tucuruí Airport" },
        { "TXF", "9 de Maio - Teixeira de Freitas Airport" },
        { "UBA", "Mário de Almeida Franco Airport" },
        { "UBT", "Ubatuba Gastão Madeira State Airport" },
        { "UDI", "Ten. Cel. Aviador César Bombonato Airport" },
        { "UMU", "Orlando de Carvalho Airport" },
        { "UNA", "Una-Comandatuba Airport" },
        { "URG", "Rubem Berta Airport" },
        { "UVI", "José Cleto Airport" },
        { "VAG", "Major Brigadeiro Trompowsky Airport" },
        { "VAL", "Valença Airport" },
        { "VCC", "Vacaria Airport" },
        { "VCP", "Viracopos International Airport" },
        { "VDC", "Glauber de Andrade Rocha Airport" },
        { "VIA", "Videira Airport" },
        { "VIX", "Eurico de Aguiar Salles International Airport" },
        { "VLP", "Vila Rica Airport" },
        { "VOT", "Domingos Pignatari Airport" },
        { "VRZ", "Padre Israel Airport" },
        { "XAP", "Serafin Enoss Bertaso Airport" },
        { "XIG", "Xinguara Municipal Airport" },
        { "ZMD", "Sena Madureira Airport" },
        { "ACC", "Kotoka International Airport" },
        { "ADD", "Addis Ababa Bole International Airport" },
        { "AEP", "Aeroparque Jorge Newbery" },
        { "AGP", "Málaga-Costa del Sol Airport" },
        { "AGT", "Guaraní International Airport" },
        { "AKL", "Auckland International Airport" },
        { "ALG", "Houari Boumediene Airport" },
        { "AMM", "Queen Alia International Airport" },
        { "AMS", "Amsterdam Airport Schiphol" },
        { "ARN", "Stockholm-Arlanda Airport" },
        { "ASU", "Silvio Pettirossi International Airport" },
        { "ATH", "Athens Eleftherios Venizelos International Airport" },
        { "ATL", "Hartsfield Jackson Atlanta International Airport" },
        { "AUA", "Queen Beatrix International Airport" },
        { "AUH", "Zayed International Airport" },
        { "BAH", "Bahrain International Airport" },
        { "BCN", "Josep Tarradellas Barcelona-El Prat Airport" },
        { "BEG", "Belgrade Nikola Tesla Airport" },
        { "BER", "Berlin Brandenburg Airport" },
        { "BEY", "Beirut Rafic Hariri International Airport" },
        { "BGI", "Grantley Adams International Airport" },
        { "BKK", "Suvarnabhumi Airport" },
        { "BLQ", "Bologna Guglielmo Marconi Airport" },
        { "BLR", "Kempegowda International Airport Bengaluru" },
        { "BNE", "Brisbane International Airport" },
        { "BOG", "El Dorado International Airport" },
        { "BOM", "Chhatrapati Shivaji Maharaj International Airport" },
        { "BOS", "Boston Logan International Airport" },
        { "BRC", "Teniente Luis Candelaria International Airport" },
        { "BRU", "Brussels Airport" },
        { "BUD", "Budapest Liszt Ferenc International Airport" },
        { "BZE", "Philip S. W. Goldson International Airport" },
        { "CAI", "Cairo International Airport" },
        { "CAN", "Guangzhou Baiyun International Airport" },
        { "CBB", "Jorge Wilsterman International Airport" },
        { "CCS", "Maiquetía Simón Bolívar International Airport" },
        { "CDG", "Charles de Gaulle International Airport" },
        { "CGK", "Soekarno-Hatta International Airport" },
        { "CHC", "Christchurch International Airport" },
        { "CIA", "Ciampino–G. B. Pastine International Airport" },
        { "CLO", "Alfonso Bonilla Aragon International Airport" },
        { "CMB", "Bandaranaike International Colombo Airport" },
        { "CMN", "Mohammed V International Airport" },
        { "COR", "Ingeniero Aeronáutico Ambrosio L.V. Taravella International Airport" },
        { "CPH", "Copenhagen Kastrup Airport" },
        { "CPT", "Cape Town International Airport" },
        { "CTG", "Rafael Nuñez International Airport" },
        { "CUN", "Cancún International Airport" },
        { "CUR", "Hato International Airport" },
        { "CUZ", "Alejandro Velasco Astete International Airport" },
        { "DAC", "Hazrat Shahjalal International Airport" },
        { "DBV", "Dubrovnik Ruđer Bošković Airport" },
        { "DCA", "Ronald Reagan Washington National Airport" },
        { "DEL", "Indira Gandhi International Airport" },
        { "DEN", "Denver International Airport" },
        { "DFW", "Dallas Fort Worth International Airport" },
        { "DME", "Domodedovo International Airport" },
        { "DMK", "Don Mueang International Airport" },
        { "DOH", "Hamad International Airport" },
        { "DPS", "Denpasar I Gusti Ngurah Rai International Airport" },
        { "DSS", "Blaise Diagne International Airport" },
        { "DTW", "Detroit Metropolitan Wayne County Airport" },
        { "DUB", "Dublin Airport" },
        { "DUS", "Düsseldorf Airport" },
        { "DXB", "Dubai International Airport" },
        { "EDI", "Edinburgh Airport" },
        { "EWR", "Newark Liberty International Airport" },
        { "EZE", "Ezeiza International Airport - Ministro Pistarini" },
        { "FAO", "Faro - Gago Coutinho International Airport" },
        { "FCO", "Rome–Fiumicino Leonardo da Vinci International Airport" },
        { "FLL", "Fort Lauderdale Hollywood International Airport" },
        { "FLR", "Florence Airport, Peretola" },
        { "FNC", "Cristiano Ronaldo International Airport" },
        { "FRA", "Frankfurt Main Airport" },
        { "FTE", "El Calafate - Commander Armando Tola International Airport" },
        { "GDL", "Guadalajara International Airport" },
        { "GMP", "Seoul Gimpo International Airport" },
        { "GUA", "La Aurora International Airport" },
        { "GVA", "Geneva International Airport" },
        { "GYE", "José Joaquín de Olmedo International Airport" },
        { "HAM", "Hamburg Helmut Schmidt Airport" },
        { "HAN", "Noi Bai International Airport" },
        { "HAV", "José Martí International Airport" },
        { "HEL", "Helsinki Vantaa Airport" },
        { "HKG", "Hong Kong International Airport" },
        { "HKT", "Phuket International Airport" },
        { "HND", "Tokyo Haneda International Airport" },
        { "HNL", "Daniel K. Inouye International Airport" },
        { "IAD", "Washington Dulles International Airport" },
        { "IAH", "George Bush Intercontinental Airport" },
        { "ICN", "Incheon International Airport" },
        { "IPC", "Mataveri International Airport" },
        { "IST", "İstanbul Airport" },
        { "JED", "King Abdulaziz International Airport" },
        { "JFK", "John F. Kennedy International Airport" },
        { "JMK", "Mykonos Island National Airport" },
        { "JNB", "O.R. Tambo International Airport" },
        { "JTR", "Santorini International Airport" },
        { "KEF", "Keflavik International Airport" },
        { "KIN", "Norman Manley International Airport" },
        { "KIX", "Kansai International Airport" },
        { "KTM", "Tribhuvan International Airport" },
        { "KUL", "Kuala Lumpur International Airport" },
        { "KWI", "Kuwait International Airport" },
        { "LAD", "Quatro de Fevereiro International Airport" },
        { "LAS", "Harry Reid International Airport" },
        { "LAX", "Los Angeles International Airport" },
        { "LCY", "London City Airport" },
        { "LED", "Pulkovo Airport" },
        { "LGA", "LaGuardia Airport" },
        { "LGW", "London Gatwick Airport" },
        { "LHR", "London Heathrow Airport" },
        { "LIM", "Jorge Chávez International Airport" },
        { "LIN", "Milano Linate Airport" },
        { "LIS", "Lisbon Humberto Delgado Airport" },
        { "LOS", "Murtala Muhammed International Airport" },
        { "LPB", "El Alto International Airport" },
        { "LTN", "London Luton Airport" },
        { "LYS", "Lyon Saint-Exupéry Airport" },
        { "MAD", "Adolfo Suárez Madrid–Barajas Airport" },
        { "MAN", "Manchester Airport" },
        { "MBJ", "Sangster International Airport" },
        { "MCO", "Orlando International Airport" },
        { "MCT", "Muscat International Airport" },
        { "MDE", "Jose Maria Córdova International Airport" },
        { "MDW", "Chicago Midway International Airport" },
        { "MDZ", "Governor Francisco Gabrielli International Airport" },
        { "MEL", "Melbourne Airport" },
        { "MEX", "Mexico City Benito Juárez International Airport" },
        { "MGA", "Augusto C. Sandino (Managua) International Airport" },
        { "MIA", "Miami International Airport" },
        { "MLE", "Velana International Airport" },
        { "MNL", "Ninoy Aquino International Airport" },
        { "MPM", "Maputo Airport" },
        { "MRS", "Marseille Provence Airport" },
        { "MRU", "Sir Seewoosagur Ramgoolam International Airport" },
        { "MSP", "Minneapolis–Saint Paul International Airport / Wold–Chamberlain Field" },
        { "MUC", "Munich Airport" },
        { "MVD", "Carrasco General Cesáreo L. Berisso International Airport" },
        { "MXP", "Milan Malpensa International Airport" },
        { "NAN", "Nadi International Airport" },
        { "NAP", "Naples International Airport" },
        { "NAS", "Lynden Pindling International Airport" },
        { "NBO", "Jomo Kenyatta International Airport" },
        { "NCE", "Nice-Côte d'Azur Airport" },
        { "NRT", "Narita International Airport" },
        { "OPO", "Francisco de Sá Carneiro Airport" },
        { "ORD", "Chicago O'Hare International Airport" },
        { "ORY", "Paris-Orly Airport" },
        { "OSL", "Oslo-Gardermoen International Airport" },
        { "OTP", "Bucharest Henri Coandă International Airport" },
        { "PDL", "João Paulo II Airport" },
        { "PDP", "Capitan Corbeta CA Curbelo International Airport" },
        { "PEK", "Beijing Capital International Airport" },
        { "PER", "Perth International Airport" },
        { "PHL", "Philadelphia International Airport" },
        { "PHX", "Phoenix Sky Harbor International Airport" },
        { "PKX", "Beijing Daxing International Airport" },
        { "PMI", "Palma de Mallorca Airport" },
        { "POS", "Piarco International Airport" },
        { "PPT", "Fa'a'ā International Airport" },
        { "PRG", "Václav Havel Airport Prague" },
        { "PTY", "Tocumen International Airport" },
        { "PUJ", "Punta Cana International Airport" },
        { "PUQ", "President Carlos Ibáñez International Airport" },
        { "PVG", "Shanghai Pudong International Airport" },
        { "RAI", "Nelson Mandela International Airport" },
        { "RAK", "Marrakesh Menara Airport" },
        { "RUH", "King Khalid International Airport" },
        { "SAL", "El Salvador International Airport Saint Óscar Arnulfo Romero y Galdámez" },
        { "SAN", "San Diego International Airport" },
        { "SAW", "Istanbul Sabiha Gökçen International Airport" },
        { "SCL", "Comodoro Arturo Merino Benítez International Airport" },
        { "SDQ", "Las Américas International Airport" },
        { "SEA", "Seattle–Tacoma International Airport" },
        { "SEZ", "Seychelles International Airport" },
        { "SFO", "San Francisco International Airport" },
        { "SGN", "Tan Son Nhat International Airport" },
        { "SHA", "Shanghai Hongqiao International Airport" },
        { "SID", "Amílcar Cabral International Airport" },
        { "SIN", "Singapore Changi Airport" },
        { "SJO", "Juan Santamaría International Airport" },
        { "SJU", "Luis Munoz Marin International Airport" },
        { "STN", "London Stansted Airport" },
        { "SVO", "Sheremetyevo International Airport" },
        { "SVQ", "Seville Airport" },
        { "SXM", "Princess Juliana International Airport" },
        { "SYD", "Sydney Kingsford Smith International Airport" },
        { "TLV", "Ben Gurion International Airport" },
        { "TPE", "Taiwan Taoyuan International Airport" },
        { "TUN", "Tunis Carthage International Airport" },
        { "UIO", "Mariscal Sucre International Airport" },
        { "USH", "Ushuaia - Malvinas Argentinas International Airport" },
        { "VCE", "Venice Marco Polo Airport" },
        { "VIE", "Vienna International Airport" },
        { "VLC", "Valencia Airport" },
        { "VVI", "Viru Viru International Airport" },
        { "WAW", "Warsaw Chopin Airport" },
        { "YOW", "Ottawa Macdonald-Cartier International Airport" },
        { "YQB", "Quebec Jean Lesage International Airport" },
        { "YUL", "Montreal / Pierre Elliott Trudeau International Airport" },
        { "YVR", "Vancouver International Airport" },
        { "YYC", "Calgary International Airport" },
        { "YYZ", "Toronto Pearson International Airport" },
        { "ZAG", "Zagreb Franjo Tuđman International Airport" },
        { "ZQN", "Queenstown Airport" },
        { "ZRH", "Zürich Airport" },
    };
}
