using System;
using System.Collections.Generic;
using System.Globalization;
using System.Text;
using System.Text.RegularExpressions;

public static partial class Quote
{
    // Fonte: OurAirports, consulta em 09/09/2026 (domínio público).
    // Cobertura e critérios em MANUTENCAO.md. Os valores são cidades atendidas,
    // preservando o formato Cidade (IATA), e não os nomes oficiais dos terminais.
    public static Dictionary<string, string> Cities = new Dictionary<string, string>
    {
        // Brasil
        { "AAI", "Arraias" },
        { "AAX", "Araxá" },
        { "AFL", "Alta Floresta" },
        { "AIF", "Assis" },
        { "AIR", "Aripuanã" },
        { "AIY", "Araçuaí" },
        { "AJU", "Aracaju" },
        { "ALQ", "Alegrete" },
        { "ALT", "Alenquer" },
        { "AMJ", "Almenara" },
        { "APQ", "Arapiraca" },
        { "APS", "Anápolis" },
        { "APU", "Apucarana" },
        { "APX", "Arapongas" },
        { "APY", "Alto Parnaíba" },
        { "AQA", "Araraquara" },
        { "AQM", "Ariquemes" },
        { "ARS", "Aragarças" },
        { "ARU", "Araçatuba" },
        { "ARX", "Aracati" },
        { "ATM", "Altamira" },
        { "AUX", "Araguaína" },
        { "AXE", "Xanxerê" },
        { "AZL", "Sapezal" },
        { "BAT", "Barretos" },
        { "BAZ", "Barcelos" },
        { "BCR", "Boca do Acre" },
        { "BDC", "Barra do Corda" },
        { "BEL", "Belém" },
        { "BFH", "Curitiba" },
        { "BGV", "Bento Gonçalves" },
        { "BGX", "Bagé" },
        { "BJP", "Bragança Paulista" },
        { "BMS", "Brumado" },
        { "BNU", "Blumenau" },
        { "BPG", "Barra do Garças" },
        { "BPS", "Porto Seguro" },
        { "BQQ", "Barra" },
        { "BRA", "Barreiras" },
        { "BRB", "Barreirinhas" },
        { "BSB", "Brasília" },
        { "BSS", "Balsas" },
        { "BVB", "Boa Vista" },
        { "BVH", "Vilhena" },
        { "BVM", "Belmonte" },
        { "BVS", "Breves" },
        { "BYO", "Bonito" },
        { "BZC", "Cabo Frio" },
        { "CAC", "Cascavel" },
        { "CAF", "Carauari" },
        { "CAU", "Caruaru" },
        { "CAW", "Campos dos Goytacazes" },
        { "CBW", "Campo Mourão" },
        { "CCI", "Concórdia" },
        { "CCM", "Criciúma" },
        { "CCX", "Cáceres" },
        { "CDI", "Cachoeiro do Itapemirim" },
        { "CDJ", "Conceição do Araguaia" },
        { "CEL", "Canela" },
        { "CFB", "Cabo Frio" },
        { "CFC", "Caçador" },
        { "CFO", "Confresa" },
        { "CGB", "Cuiabá" },
        { "CGH", "São Paulo" },
        { "CGR", "Campo Grande" },
        { "CHD", "Mucugê" },
        { "CIZ", "Coari" },
        { "CJZ", "Cajazeiras" },
        { "CKO", "Cornélio Procópio" },
        { "CKS", "Parauapebas" },
        { "CLN", "Carolina" },
        { "CLV", "Caldas Novas" },
        { "CMC", "Camocim" },
        { "CMG", "Corumbá" },
        { "CMP", "Santana do Araguaia" },
        { "CMT", "Cametá" },
        { "CNF", "Belo Horizonte" },
        { "CNV", "Canavieiras" },
        { "CPU", "Cururupu" },
        { "CPV", "Campina Grande" },
        { "CQA", "Canarana" },
        { "CQS", "Costa Marques" },
        { "CRQ", "Caravelas" },
        { "CSS", "Cassilândia" },
        { "CSU", "Santa Cruz do Sul" },
        { "CTP", "Carutapera" },
        { "CTQ", "Santa Vitória do Palmar" },
        { "CWB", "Curitiba" },
        { "CXJ", "Caxias do Sul" },
        { "CZB", "Cruz Alta" },
        { "CZS", "Cruzeiro do Sul" },
        { "DIQ", "Divinópolis" },
        { "DMT", "Diamantino" },
        { "DNO", "Dianópolis" },
        { "DOU", "Dourados" },
        { "DTI", "Diamantina" },
        { "EEA", "Correia Pinto" },
        { "ERM", "Erechim" },
        { "ERN", "Eirunepé" },
        { "FBA", "Fonte Boa" },
        { "FBE", "Francisco Beltrão" },
        { "FEC", "Feira de Santana" },
        { "FEJ", "Feijó" },
        { "FEN", "Fernando de Noronha" },
        { "FLB", "Floriano" },
        { "FLN", "Florianópolis" },
        { "FOR", "Fortaleza" },
        { "FRC", "Franca" },
        { "GCV", "Gravatai" },
        { "GDP", "Guadalupe" },
        { "GDR", "Angra dos Reis" },
        { "GEL", "Santo Ângelo" },
        { "GGB", "Água Boa" },
        { "GGF", "Almeirim" },
        { "GGH", "Cianorte" },
        { "GGJ", "Guaíra" },
        { "GIG", "Rio de Janeiro" },
        { "GJM", "Guajará-Mirim" },
        { "GMS", "Guimarães" },
        { "GNM", "Guanambi" },
        { "GPB", "Guarapuava" },
        { "GRP", "Gurupi" },
        { "GRU", "São Paulo" },
        { "GUJ", "Guaratinguetá" },
        { "GUZ", "Guarapari" },
        { "GVR", "Governador Valadares" },
        { "GYN", "Goiânia" },
        { "HRZ", "Horizontina" },
        { "HUW", "Humaitá" },
        { "IDO", "Cristalândia" },
        { "IGU", "Foz do Iguaçu" },
        { "IJU", "Ijuí" },
        { "IMP", "Imperatriz" },
        { "IOS", "Ilhéus" },
        { "IPG", "Santo Antônio do Içá" },
        { "IPN", "Ipatinga" },
        { "IPU", "Ipiaú" },
        { "IRE", "Irecê" },
        { "IRZ", "Santa Isabel do Rio Negro" },
        { "ITA", "Itacoatiara" },
        { "ITB", "Itaituba" },
        { "ITE", "Ituberá" },
        { "ITI", "Itambacuri" },
        { "ITJ", "Itajaí" },
        { "ITN", "Itabuna" },
        { "ITP", "Itaperuna" },
        { "ITQ", "Itaqui" },
        { "ITR", "Itumbiara" },
        { "IUP", "Apuí" },
        { "IZA", "Juiz de Fora" },
        { "JAW", "Araripina" },
        { "JBS", "São Borja" },
        { "JCB", "Joaçaba" },
        { "JCM", "Jacobina" },
        { "JCR", "Jacareacanga" },
        { "JCS", "Crateús" },
        { "JDF", "Juiz de Fora" },
        { "JDO", "Juazeiro do Norte" },
        { "JDR", "São João Del Rei" },
        { "JEQ", "Jequié" },
        { "JHF", "São Roque" },
        { "JIA", "Juína" },
        { "JJD", "Cruz" },
        { "JJG", "Jaguaruna" },
        { "JLS", "Jales" },
        { "JMA", "Manhuaçu" },
        { "JMR", "Maricá" },
        { "JNA", "Januária" },
        { "JOI", "Joinville" },
        { "JPA", "João Pessoa" },
        { "JPE", "Paragominas" },
        { "JPO", "Patos" },
        { "JPR", "Ji-Paraná" },
        { "JPY", "Paraty" },
        { "JRN", "Juruena" },
        { "JRT", "Juruti" },
        { "JSB", "São Benedito" },
        { "JSO", "Sobral" },
        { "JTA", "Tauá" },
        { "JTC", "Bauru" },
        { "JTI", "Jataí" },
        { "JTN", "Itanhaém" },
        { "JUA", "Juara" },
        { "LAJ", "Lages" },
        { "LAZ", "Bom Jesus da Lapa" },
        { "LBR", "Lábrea" },
        { "LCB", "Pontes e Lacerda" },
        { "LDB", "Londrina" },
        { "LEC", "Lençóis" },
        { "LEP", "Leopoldina" },
        { "LHN", "Linhares" },
        { "LIP", "Lins" },
        { "LOI", "Lontras" },
        { "LVR", "Lucas do Rio Verde" },
        { "MAB", "Marabá" },
        { "MAO", "Manaus" },
        { "MBK", "Matupá" },
        { "MBZ", "Maués" },
        { "MCP", "Macapá" },
        { "MCZ", "Maceió" },
        { "MEA", "Macaé" },
        { "MEU", "Almeirim" },
        { "MGF", "Maringá" },
        { "MII", "Marília" },
        { "MNX", "Manicoré" },
        { "MOC", "Montes Claros" },
        { "MQH", "Minaçu" },
        { "MTE", "Monte Alegre" },
        { "MTG", "Vila Bela da Santíssima Trindade" },
        { "MUU", "Maraú" },
        { "MVF", "Mossoró" },
        { "MVS", "Mucuri" },
        { "MXQ", "Cairu" },
        { "NAT", "Natal" },
        { "NNU", "Nanuque" },
        { "NOK", "Nova Xavantina" },
        { "NPR", "Novo Progresso" },
        { "NQL", "Niquelândia" },
        { "NSR", "São Raimundo Nonato" },
        { "NVM", "Nova Mutum" },
        { "NVP", "Novo Aripuanã" },
        { "NVT", "Navegantes" },
        { "OAL", "Cacoal" },
        { "OBI", "Óbidos" },
        { "OIA", "Ourilândia do Norte" },
        { "OLC", "São Paulo de Olivença" },
        { "OPP", "Salinópolis" },
        { "OPS", "Sinop" },
        { "ORX", "Oriximiná" },
        { "OTT", "Cotriguaçu" },
        { "OUS", "Ourinhos" },
        { "OYK", "Oiapoque" },
        { "PAV", "Paulo Afonso" },
        { "PBA", "Cairu" },
        { "PBB", "Paranaíba" },
        { "PBQ", "Pimenta Bueno" },
        { "PBX", "Porto Alegre do Norte" },
        { "PCS", "Picos" },
        { "PDF", "Prado" },
        { "PDR", "Presidente Dutra" },
        { "PET", "Pelotas" },
        { "PFB", "Passo Fundo" },
        { "PGZ", "Ponta Grossa" },
        { "PHB", "Parnaíba" },
        { "PHI", "Pinheiro" },
        { "PIN", "Parintins" },
        { "PIV", "Pirapora" },
        { "PLL", "Manaus" },
        { "PLU", "Belo Horizonte" },
        { "PMG", "Ponta Porã" },
        { "PMW", "Palmas" },
        { "PNB", "Porto Nacional" },
        { "PNG", "Paranaguá" },
        { "PNZ", "Petrolina" },
        { "POA", "Porto Alegre" },
        { "POJ", "Patos de Minas" },
        { "POO", "Poços de Caldas" },
        { "PPB", "Presidente Prudente" },
        { "PPY", "Pouso Alegre" },
        { "PSW", "Passos" },
        { "PTO", "Pato Branco" },
        { "PTQ", "Porto de Moz" },
        { "PVH", "Porto Velho" },
        { "PVI", "Paranavaí" },
        { "PYT", "Paracatu" },
        { "QCH", "Colatina" },
        { "QCP", "Currais Novos" },
        { "QDB", "Cachoeira do Sul" },
        { "QDV", "Jundiaí" },
        { "QGF", "Montenegro" },
        { "QGP", "Garanhuns" },
        { "QHV", "Novo Hamburgo" },
        { "QIG", "Iguatu" },
        { "QIT", "Itapetinga" },
        { "QNS", "Porto Alegre" },
        { "QSC", "São Carlos" },
        { "RAO", "Ribeirão Preto" },
        { "RBB", "Borba" },
        { "RBR", "Rio Branco" },
        { "RDC", "Redenção" },
        { "REC", "Recife" },
        { "REZ", "Resende" },
        { "RIA", "Santa Maria" },
        { "RIG", "Rio Grande" },
        { "ROO", "Rondonópolis" },
        { "RPU", "Urucu" },
        { "RRJ", "Rio de Janeiro" },
        { "RTE", "São Paulo" },
        { "RVD", "Rio Verde" },
        { "SBJ", "São Mateus" },
        { "SDU", "Rio de Janeiro" },
        { "SET", "Serra Talhada" },
        { "SFK", "Soure" },
        { "SFV", "Santa Fé do Sul" },
        { "SJK", "São José dos Campos" },
        { "SJL", "São Gabriel da Cachoeira" },
        { "SJP", "São José do Rio Preto" },
        { "SLZ", "São Luís" },
        { "SMT", "Sorriso" },
        { "SNZ", "Rio de Janeiro" },
        { "SOD", "Sorocaba" },
        { "SQM", "São Miguel do Araguaia" },
        { "SQX", "São Miguel do Oeste" },
        { "SQY", "São Lourenço do Sul" },
        { "SRA", "Santa Rosa" },
        { "SSA", "Salvador" },
        { "SSO", "São Lourenço" },
        { "SSZ", "Guarujá" },
        { "STM", "Santarém" },
        { "SXO", "São Félix do Araguaia" },
        { "SXX", "São Félix do Xingu" },
        { "TBT", "Tabatinga" },
        { "TEC", "Telêmaco Borba" },
        { "TFF", "Tefé" },
        { "TFL", "Teófilo Otoni" },
        { "TGQ", "Tangará da Serra" },
        { "THE", "Teresina" },
        { "TJL", "Três Lagoas" },
        { "TLZ", "Catalão" },
        { "TMT", "Oriximiná" },
        { "TOW", "Toledo" },
        { "TRQ", "Tarauacá" },
        { "TSQ", "Torres" },
        { "TUR", "Tucuruí" },
        { "TXF", "Teixeira de Freitas" },
        { "UBA", "Uberaba" },
        { "UBT", "Ubatuba" },
        { "UDI", "Uberlândia" },
        { "UMU", "Umuarama" },
        { "UNA", "Una" },
        { "URG", "Uruguaiana" },
        { "UVI", "União da Vitória" },
        { "VAG", "Varginha" },
        { "VAL", "Valença" },
        { "VCC", "Vacaria" },
        { "VCP", "Campinas" },
        { "VDC", "Vitória da Conquista" },
        { "VIA", "Videira" },
        { "VIX", "Vitória" },
        { "VLP", "Vila Rica" },
        { "VOT", "Votuporanga" },
        { "VRZ", "Lavras" },
        { "XAP", "Chapecó" },
        { "XIG", "Xinguara" },
        { "ZMD", "Sena Madureira" },
        // Internacionais
        { "ACC", "Acra" },
        { "ADD", "Adis Abeba" },
        { "AEP", "Buenos Aires" },
        { "AGP", "Málaga" },
        { "AGT", "Ciudad del Este" },
        { "AKL", "Auckland" },
        { "ALG", "Argel" },
        { "AMM", "Amã" },
        { "AMS", "Amsterdã" },
        { "ARN", "Estocolmo" },
        { "ASU", "Assunção" },
        { "ATH", "Atenas" },
        { "ATL", "Atlanta" },
        { "AUA", "Aruba" },
        { "AUH", "Abu Dhabi" },
        { "BAH", "Manama" },
        { "BCN", "Barcelona" },
        { "BEG", "Belgrado" },
        { "BER", "Berlim" },
        { "BEY", "Beirute" },
        { "BGI", "Bridgetown" },
        { "BKK", "Bangkok" },
        { "BLQ", "Bolonha" },
        { "BLR", "Bengaluru" },
        { "BNE", "Brisbane" },
        { "BOG", "Bogotá" },
        { "BOM", "Mumbai" },
        { "BOS", "Boston" },
        { "BRC", "Bariloche" },
        { "BRU", "Bruxelas" },
        { "BUD", "Budapeste" },
        { "BZE", "Cidade de Belize" },
        { "CAI", "Cairo" },
        { "CAN", "Cantão" },
        { "CBB", "Cochabamba" },
        { "CCS", "Caracas" },
        { "CDG", "Paris" },
        { "CGK", "Jacarta" },
        { "CHC", "Christchurch" },
        { "CIA", "Roma" },
        { "CLO", "Cali" },
        { "CMB", "Colombo" },
        { "CMN", "Casablanca" },
        { "COR", "Córdoba" },
        { "CPH", "Copenhague" },
        { "CPT", "Cidade do Cabo" },
        { "CTG", "Cartagena" },
        { "CUN", "Cancún" },
        { "CUR", "Curaçao" },
        { "CUZ", "Cusco" },
        { "DAC", "Daca" },
        { "DBV", "Dubrovnik" },
        { "DCA", "Washington" },
        { "DEL", "Nova Délhi" },
        { "DEN", "Denver" },
        { "DFW", "Dallas/Fort Worth" },
        { "DME", "Moscou" },
        { "DMK", "Bangkok" },
        { "DOH", "Doha" },
        { "DPS", "Bali" },
        { "DSS", "Dacar" },
        { "DTW", "Detroit" },
        { "DUB", "Dublin" },
        { "DUS", "Düsseldorf" },
        { "DXB", "Dubai" },
        { "EDI", "Edimburgo" },
        { "EWR", "Newark" },
        { "EZE", "Buenos Aires" },
        { "FAO", "Faro" },
        { "FCO", "Roma" },
        { "FLL", "Fort Lauderdale" },
        { "FLR", "Florença" },
        { "FNC", "Funchal" },
        { "FRA", "Frankfurt" },
        { "FTE", "El Calafate" },
        { "GDL", "Guadalajara" },
        { "GMP", "Seul" },
        { "GUA", "Cidade da Guatemala" },
        { "GVA", "Genebra" },
        { "GYE", "Guayaquil" },
        { "HAM", "Hamburgo" },
        { "HAN", "Hanói" },
        { "HAV", "Havana" },
        { "HEL", "Helsinque" },
        { "HKG", "Hong Kong" },
        { "HKT", "Phuket" },
        { "HND", "Tóquio" },
        { "HNL", "Honolulu" },
        { "IAD", "Washington" },
        { "IAH", "Houston" },
        { "ICN", "Seul" },
        { "IPC", "Ilha de Páscoa" },
        { "IST", "Istambul" },
        { "JED", "Jidá" },
        { "JFK", "Nova York" },
        { "JMK", "Mykonos" },
        { "JNB", "Joanesburgo" },
        { "JTR", "Santorini" },
        { "KEF", "Reykjavík" },
        { "KIN", "Kingston" },
        { "KIX", "Osaka" },
        { "KTM", "Catmandu" },
        { "KUL", "Kuala Lumpur" },
        { "KWI", "Cidade do Kuwait" },
        { "LAD", "Luanda" },
        { "LAS", "Las Vegas" },
        { "LAX", "Los Angeles" },
        { "LCY", "Londres" },
        { "LED", "São Petersburgo" },
        { "LGA", "Nova York" },
        { "LGW", "Londres" },
        { "LHR", "Londres" },
        { "LIM", "Lima" },
        { "LIN", "Milão" },
        { "LIS", "Lisboa" },
        { "LOS", "Lagos" },
        { "LPB", "La Paz" },
        { "LTN", "Londres" },
        { "LYS", "Lyon" },
        { "MAD", "Madri" },
        { "MAN", "Manchester" },
        { "MBJ", "Montego Bay" },
        { "MCO", "Orlando" },
        { "MCT", "Mascate" },
        { "MDE", "Medellín" },
        { "MDW", "Chicago" },
        { "MDZ", "Mendoza" },
        { "MEL", "Melbourne" },
        { "MEX", "Cidade do México" },
        { "MGA", "Manágua" },
        { "MIA", "Miami" },
        { "MLE", "Malé" },
        { "MNL", "Manila" },
        { "MPM", "Maputo" },
        { "MRS", "Marselha" },
        { "MRU", "Maurício" },
        { "MSP", "Minneapolis" },
        { "MUC", "Munique" },
        { "MVD", "Montevidéu" },
        { "MXP", "Milão" },
        { "NAN", "Nadi" },
        { "NAP", "Nápoles" },
        { "NAS", "Nassau" },
        { "NBO", "Nairóbi" },
        { "NCE", "Nice" },
        { "NRT", "Tóquio" },
        { "OPO", "Porto" },
        { "ORD", "Chicago" },
        { "ORY", "Paris" },
        { "OSL", "Oslo" },
        { "OTP", "Bucareste" },
        { "PDL", "Ponta Delgada" },
        { "PDP", "Punta del Este" },
        { "PEK", "Pequim" },
        { "PER", "Perth" },
        { "PHL", "Filadélfia" },
        { "PHX", "Phoenix" },
        { "PKX", "Pequim" },
        { "PMI", "Palma de Maiorca" },
        { "POS", "Port of Spain" },
        { "PPT", "Papeete" },
        { "PRG", "Praga" },
        { "PTY", "Cidade do Panamá" },
        { "PUJ", "Punta Cana" },
        { "PUQ", "Punta Arenas" },
        { "PVG", "Xangai" },
        { "RAI", "Praia" },
        { "RAK", "Marrakech" },
        { "RUH", "Riade" },
        { "SAL", "San Salvador" },
        { "SAN", "San Diego" },
        { "SAW", "Istambul" },
        { "SCL", "Santiago" },
        { "SDQ", "Santo Domingo" },
        { "SEA", "Seattle" },
        { "SEZ", "Mahé" },
        { "SFO", "São Francisco" },
        { "SGN", "Cidade de Ho Chi Minh" },
        { "SHA", "Xangai" },
        { "SID", "Ilha do Sal" },
        { "SIN", "Singapura" },
        { "SJO", "San José" },
        { "SJU", "San Juan" },
        { "STN", "Londres" },
        { "SVO", "Moscou" },
        { "SVQ", "Sevilha" },
        { "SXM", "Sint Maarten" },
        { "SYD", "Sydney" },
        { "TLV", "Tel Aviv" },
        { "TPE", "Taipé" },
        { "TUN", "Túnis" },
        { "UIO", "Quito" },
        { "USH", "Ushuaia" },
        { "VCE", "Veneza" },
        { "VIE", "Viena" },
        { "VLC", "Valência" },
        { "VVI", "Santa Cruz de la Sierra" },
        { "WAW", "Varsóvia" },
        { "YOW", "Ottawa" },
        { "YQB", "Quebec" },
        { "YUL", "Montreal" },
        { "YVR", "Vancouver" },
        { "YYC", "Calgary" },
        { "YYZ", "Toronto" },
        { "ZAG", "Zagreb" },
        { "ZQN", "Queenstown" },
        { "ZRH", "Zurique" },
    };
    public static string Place(string code)
    {
        code = code.Trim().ToUpperInvariant();
        return Cities.ContainsKey(code) ? Cities[code] + " (" + code + ")" : code;
    }

    // Compatibilidade com os prints já validados. Essas substituições de OCR
    // não constituem um catálogo universal: a revisão dos aeroportos continua necessária.
    static string NormalizeAirportCode(string code)
    {
        return code.Replace("GRIJ", "GRU").Replace("CRU", "GRU").Replace("FIN", "FLN");
    }

    static string NormalizeAirportLabels(string text)
    {
        // Print de Londrina conferido em 09/09/2026: tabela sem cidades,
        // com dois códigos e, opcionalmente, duração numérica após o destino.
        // Exceção explícita, não uma correção por semelhança para qualquer IATA.
        text = Regex.Replace(text,
            @"^(?<space>\s*)(?<from>[A-Z0-9]{3}|GRIJ)(?<gap>\s+)(?<to>[A-Z0-9]{3}|GRIJ)(?<tail>\s*(?:\d[\d:.\s]*)?)$",
            match => match.Groups["space"].Value +
                NormalizeBareAirportCode(match.Groups["from"].Value) +
                match.Groups["gap"].Value +
                NormalizeBareAirportCode(match.Groups["to"].Value) +
                match.Groups["tail"].Value, RegexOptions.IgnoreCase);
        // Correções contextuais: só repare o código se a cidade ao lado confirmar.
        // US isolado não deve ser interpretado como Lisboa.
        text = Regex.Replace(text, @"\bCCH(?=\s*(?:[-–—]\s*)?(?:S[ÃA]O\s+PAULO|CONGONHAS)\b)", "CGH", RegexOptions.IgnoreCase);
        text = Regex.Replace(text, @"\b(?:US|[LI1][IS1]S)\s*[-–—]?\s+LISBOA\b", "LIS - LISBOA", RegexOptions.IgnoreCase);
        text = Regex.Replace(text, @"\b(?:UM|LIM)\s*[-–—]\s*LIMA\b", "LIM - LIMA", RegexOptions.IgnoreCase);
        text = Regex.Replace(text, @"\bLIM\s*[-–—]\s*UMA\b", "LIM - LIMA", RegexOptions.IgnoreCase);
        // A cidade confirma o destino: nunca transforme um código isolado apenas
        // porque ele se parece com outro do catálogo (que não contém todos os IATA).
        return Regex.Replace(text, @"\b[A-Za-z0-9]{3}\b", match =>
        {
            string printed = match.Value.ToUpperInvariant();
            string suffix = FoldAirportCity(text.Substring(match.Index + match.Length));
            suffix = suffix.TrimStart(' ', '\t', '-', '–', '—');
            string candidate = null;
            foreach (var airport in Cities)
            {
                string city = FoldAirportCity(airport.Value);
                if (!suffix.StartsWith(city, StringComparison.Ordinal) ||
                    (suffix.Length > city.Length && char.IsLetterOrDigit(suffix[city.Length]))) continue;
                // Um código exato confirmado pela cidade sempre prevalece.
                if (printed == airport.Key) return printed;
                if (!IsAirportOcrVariant(printed, airport.Key)) continue;
                if (candidate != null && candidate != airport.Key) candidate = "";
                else if (candidate == null) candidate = airport.Key;
            }
            return string.IsNullOrEmpty(candidate) ? match.Value : candidate;
        });
    }

    // Exceções relatadas para tabelas com apenas origem/destino e duração.
    // Não substituir C por G globalmente: isso alteraria outros IATA válidos.
    static string NormalizeBareAirportCode(string code)
    {
        if (code.Equals("LOB", StringComparison.OrdinalIgnoreCase)) return "LDB";
        if (code.Equals("CCH", StringComparison.OrdinalIgnoreCase)) return "CGH";
        return code;
    }

    static string FoldAirportCity(string value)
    {
        var result = new StringBuilder();
        foreach (char character in value.Normalize(NormalizationForm.FormD))
            if (CharUnicodeInfo.GetUnicodeCategory(character) != UnicodeCategory.NonSpacingMark)
                result.Append(char.ToUpperInvariant(character));
        return Regex.Replace(result.ToString(), @"\s+", " ").Trim();
    }

    static bool IsAirportOcrVariant(string printed, string code)
    {
        int differences = 0;
        for (int i = 0; i < code.Length; i++)
        {
            if (printed[i] == code[i]) continue;
            differences++;
            bool similar = false;
            foreach (string group in new[] { "ODQ0", "IL1", "B8", "S5", "Z2", "G6", "T7" })
                if (group.IndexOf(printed[i]) >= 0 && group.IndexOf(code[i]) >= 0) similar = true;
            if (!similar || differences > 1) return false;
        }
        return differences == 1;
    }
}
